import type { Metadata } from "next";

import "./globals.css";
import Nav from "@/components/nav";
import { nunito } from "@/components/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
